name: Sync Docker Image to Aliyun

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull ubuntu:22.04

      - name: Tag Docker image for Aliyun
        run: docker tag ubuntu:22.04 registry.cn-guangzhou.aliyuncs.com/liujx3/ljx3:ubuntu22.04

      - name: Log in to Aliyun Docker Registry
        run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.ALIYUN_REGISTRY_USER }}" registry.cn-guangzhou.aliyuncs.com --password-stdin

      - name: Push Docker image to Aliyun
        run: docker push registry.cn-guangzhou.aliyuncs.com/liujx3/ljx3:ubuntu22.04
